---
driver:
  name: "terraform"
  root_module_directory: "examples/multi-tier"

provisioner:
  name: "terraform"

platforms:
  - name: "aws"

verifier:
  name: "awspec"

suites:
  - name: "default"
    verifier:
      name: "awspec"
      patterns:
      - "tests/test_example.rb"